# Generated by Django 5.1.5 on 2025-02-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fashion',
            name='number',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
