# Generated by Django 5.1.5 on 2025-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fashions', '0002_fashion_email_fashion_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashion2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fashion_images/'),
        ),
    ]
